### PR TITLE
Change system:openshift-client to system:openshift-master

### PR DESCRIPTION
**Pull request by liggitt**
Install changes for https://github.com/openshift/origin/pull/3160. Wait until that merges to merge this.

### CODE REVIEW

**Comment by liggitt** [comment]
@sdodson FYI. Not sure if this is the right place to open this or not

**Comment by sdodson** [comment]
@liggitt If it's something that's changed since v0.5.3 then I think this is the right place. If it's something that should be fixed in v0.5.3 then lets open it against upstream.

**Comment by liggitt** [comment]
yeah, only post-rc1

**Comment by sdodson** [comment]
```
Jun 15 16:56:11 ose3-master.example.com openshift-node[4617]: masterKubeConfig: invalid value '/etc/openshift/node/node.kubeconfig': could not read file
Jun 15 16:56:11 ose3-master.example.com openshift-node[4617]: Invalid NodeConfig /etc/openshift/node/node-config.yaml

[root@ose3-master node]# ls -la /etc/openshift/node
total 32
-rw-r--r--. 1 root root 1066 Jun 15 16:55 ca.crt
-rw-r--r--. 1 root root  565 Jun 15 16:55 node-config.yaml
-rw-r--r--. 1 root root 2201 Jun 15 16:55 server.crt
-rw-------. 1 root root 1675 Jun 15 16:55 server.key
-rw-r--r--. 1 root root 1131 Jun 15 16:55 system:node:ose3-master.example.com.crt
-rw-------. 1 root root 1679 Jun 15 16:55 system:node:ose3-master.example.com.key
-rw-------. 1 root root 5828 Jun 15 16:55 system:node:ose3-master.example.com.kubeconfig
```

so we've renamed the cert and kubeconfig files again or is this unexpected?

**Comment by sdodson** [comment]
Reading #3160 this appears to be intentional. I'll update things accordingly.

**Comment by liggitt** [comment]
the filenames changed from `system:node-$hostname.{crt,key,kubeconfig}` to `system:node:$hostname.{crt,key,kubeconfig}`... was something renaming the generated kubeconfig to `node.kubeconfig` previously?

**Pull request merged**
